# --- Basic Bluetooth ---
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Zephyr"

# --- L2CAP ---
CONFIG_BT_L2CAP_DYNAMIC_CHANNEL=y

# --- Settings (Required for L2CAP Server) ---
CONFIG_SETTINGS=y
CONFIG_BT_SETTINGS=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_BT_SMP=y
# CONFIG_BT_FIXED_PASSKEY is not set

# --- Hardware RNG (Required for wolfSSL PQC) ---
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

# --- Memory & System ---
CONFIG_WOLFSSL_BUILTIN=y
CONFIG_HEAP_MEM_POOL_SIZE=0
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=12288
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_RING_BUFFER_LARGE=y

# --- Bluetooth Buffers ---
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_COUNT=2
CONFIG_BT_BUF_EVT_RX_COUNT=6
CONFIG_BT_L2CAP_TX_MTU=672

# --- Required Dependencies ---
CONFIG_GPIO=y
CONFIG_MBEDTLS_SHA1_C=y
CONFIG_PSA_WANT_ALG_SHA_1=y

CONFIG_WOLFSSL_SETTINGS_FILE="user_settings.h"
