#ifndef PQM4_PREFIX
#error "PQM4_PREFIX must identify the ML-KEM parameter set"
#endif

#define PQM4_JOIN_INNER(a, b) a##b
#define PQM4_JOIN(a, b) PQM4_JOIN_INNER(a, b)
#define PQM4_NS(symbol) PQM4_JOIN(PQM4_PREFIX, symbol)

#define crypto_kem_keypair PQM4_NS(crypto_kem_keypair)
#define crypto_kem_enc PQM4_NS(crypto_kem_enc)
#define crypto_kem_dec PQM4_NS(crypto_kem_dec)
#define verify PQM4_NS(verify)
#define cmov PQM4_NS(cmov)
#define cbd PQM4_NS(cbd)
#define kyber_shake128_absorb PQM4_NS(kyber_shake128_absorb)
#define kyber_shake256_prf PQM4_NS(kyber_shake256_prf)
#define kyber_shake256_rkprf PQM4_NS(kyber_shake256_rkprf)
#define indcpa_keypair_derand PQM4_NS(indcpa_keypair_derand)
#define indcpa_enc PQM4_NS(indcpa_enc)
#define indcpa_enc_cmp PQM4_NS(indcpa_enc_cmp)
#define indcpa_dec PQM4_NS(indcpa_dec)
#define matacc PQM4_NS(matacc)
#define ntt PQM4_NS(ntt)
#define invntt PQM4_NS(invntt)
#define poly_compress PQM4_NS(poly_compress)
#define poly_decompress PQM4_NS(poly_decompress)
#define poly_packcompress PQM4_NS(poly_packcompress)
#define poly_unpackdecompress PQM4_NS(poly_unpackdecompress)
#define cmp_poly_compress PQM4_NS(cmp_poly_compress)
#define cmp_poly_packcompress PQM4_NS(cmp_poly_packcompress)
#define poly_tobytes PQM4_NS(poly_tobytes)
#define poly_frombytes PQM4_NS(poly_frombytes)
#define poly_frombytes_mul PQM4_NS(poly_frombytes_mul)
#define poly_frombytes_mul_acc PQM4_NS(poly_frombytes_mul_acc)
#define poly_noise PQM4_NS(poly_noise)
#define poly_ntt PQM4_NS(poly_ntt)
#define poly_invntt PQM4_NS(poly_invntt)
#define poly_basemul PQM4_NS(poly_basemul)
#define poly_basemul_acc PQM4_NS(poly_basemul_acc)
#define poly_fromplant PQM4_NS(poly_fromplant)
#define poly_reduce PQM4_NS(poly_reduce)
#define poly_add PQM4_NS(poly_add)
#define poly_sub PQM4_NS(poly_sub)
#define poly_frommsg PQM4_NS(poly_frommsg)
#define poly_tomsg PQM4_NS(poly_tomsg)
#define poly_zeroize PQM4_NS(poly_zeroize)
#define polyvec_compress PQM4_NS(polyvec_compress)
#define polyvec_decompress PQM4_NS(polyvec_decompress)
#define polyvec_tobytes PQM4_NS(polyvec_tobytes)
#define polyvec_frombytes PQM4_NS(polyvec_frombytes)
#define polyvec_ntt PQM4_NS(polyvec_ntt)
#define polyvec_invntt PQM4_NS(polyvec_invntt)
#define polyvec_reduce PQM4_NS(polyvec_reduce)
#define polyvec_add PQM4_NS(polyvec_add)
#define asm_barrett_reduce PQM4_NS(asm_barrett_reduce)
#define asm_fromplant PQM4_NS(asm_fromplant)
#define basemul_asm PQM4_NS(basemul_asm)
#define basemul_asm_acc PQM4_NS(basemul_asm_acc)
#define cmov_int16 PQM4_NS(cmov_int16)
#define frombytes_mul_asm PQM4_NS(frombytes_mul_asm)
#define frombytes_mul_asm_acc PQM4_NS(frombytes_mul_asm_acc)
#define invntt_fast PQM4_NS(invntt_fast)
#define matacc_asm PQM4_NS(matacc_asm)
#define matacc_asm_acc PQM4_NS(matacc_asm_acc)
#define ntt_fast PQM4_NS(ntt_fast)
#define pointwise_add PQM4_NS(pointwise_add)
#define pointwise_sub PQM4_NS(pointwise_sub)
#define zetas PQM4_NS(zetas)
#define zetas_asm PQM4_NS(zetas_asm)
#define zetas_inv_CT_asm PQM4_NS(zetas_inv_CT_asm)
