listener 8883
allow_anonymous false
password_file /home/vini/pqc_ble_mqtt/certs/passwd
cafile /home/vini/pqc_ble_mqtt/certs/ca.crt
certfile /home/vini/pqc_ble_mqtt/certs/server.crt
keyfile /home/vini/pqc_ble_mqtt/certs/server.key
require_certificate true
use_identity_as_username true
