#ifndef CLIENT_CERT_H
#define CLIENT_CERT_H

const char client_pem[] =
"-----BEGIN CERTIFICATE-----n"
"MIIBcTCCARagAwIBAgIUSi336R3BRG7LebXnuXh0fVjNVDEwCgYIKoZIzj0EAwIw\n"
"EzERMA8GA1UEAwwITXlSb290Q0EwHhcNMjYwNjE1MjA0NDE4WhcNMjcwNjE1MjA0\n"
"NDE4WjAZMRcwFQYDVQQDDA5ucmY1MzQwX2NsaWVudDBZMBMGByqGSM49AgEGCCqG\n"
"SM49AwEHA0IABNG9Aab/LtLnV1fkPqy11lmehlWoOOfsbJ66ZK9/y8x1ueN6gwlG\n"
"eKHQJoE7Jkpux000VNo36RRXuh85vIzvdsSjQjBAMB0GA1UdDgQWBBRjQI4joTWl\n"
"K6lVN/CNjvI/0fZoUTAfBgNVHSMEGDAWgBQ8i67UCrvLa0/RGRBjKpiaGfa4cDAK\n"
"BggqhkjOPQQDAgNJADBGAiEAohCwEQEi6DpkR+oFvQXeDSvUq8EagUlZKocbrIK3\n"
"M+ACIQCv6CZb8YJ6MGQeL90XJztiuLhcOWCcaTC1nyArjDtPgQ==\n"
"-----END CERTIFICATE-----\n";
#endif
